[colors.primary]
background = "#170306"
foreground = "#ffe9e7"
dim_foreground = "#ffe9e7"
bright_foreground = "#ffe9e7"

[colors.cursor]
text = "#170306"
cursor = "#ffe9e7"

[colors.vi_mode_cursor]
text = "#170306"
cursor = "#ffe9e7"

[colors.search.matches]
foreground = "#170306"
background = "#f3d8da"

[colors.search.focused_match]
foreground = "#ffe9e7"
background = "#6f0d1f"

[colors.footer_bar]
foreground = "#ffe9e7"
background = "#6f0d1f"

[colors.selection]
text = "#170306"
background = "#f3d8da"

[colors.normal]
black = "#ffe9e7"
red = "#ffe9e7"
green = "#ffe9e7"
yellow = "#ffe9e7"
blue = "#ffe9e7"
magenta = "#ffe9e7"
cyan = "#ffe9e7"
white = "#ffe9e7"

[colors.bright]
black = "#ffe9e7"
red = "#ffe9e7"
green = "#ffe9e7"
yellow = "#ffe9e7"
blue = "#ffe9e7"
magenta = "#ffe9e7"
cyan = "#ffe9e7"
white = "#ffe9e7"

[colors.dim]
black = "#ffe9e7"
red = "#ffe9e7"
green = "#ffe9e7"
yellow = "#ffe9e7"
blue = "#ffe9e7"
magenta = "#ffe9e7"
cyan = "#ffe9e7"
white = "#ffe9e7"
