accent = "#fff1e8"
cursor = "#fff1e8"
foreground = "#fff1e8"
background = "#241813"
selection_foreground = "#241813"
selection_background = "#f3dfcf"

color0 = "#1a110d"
color1 = "#fff1e8"
color2 = "#f0d7c6"
color3 = "#d78a59"
color4 = "#7e3d21"
color5 = "#fff1e8"
color6 = "#f0d7c6"
color7 = "#fff1e8"
color8 = "#7e3d21"
color9 = "#fff1e8"
color10 = "#f0d7c6"
color11 = "#d78a59"
color12 = "#a75c36"
color13 = "#fff1e8"
color14 = "#f0d7c6"
color15 = "#fff1e8"
