accent = "#e23f5a"
cursor = "#e23f5a"
foreground = "#ffe9e7"
background = "#2b050a"
selection_foreground = "#2b050a"
selection_background = "#f6d7db"

color0 = "#3b0911"
color1 = "#ffe9e7"
color2 = "#f2c4c9"
color3 = "#c61d3f"
color4 = "#8f112a"
color5 = "#ffe9e7"
color6 = "#f2c4c9"
color7 = "#ffe9e7"
color8 = "#8f112a"
color9 = "#ffe9e7"
color10 = "#f2c4c9"
color11 = "#c61d3f"
color12 = "#e23f5a"
color13 = "#ffe9e7"
color14 = "#f2c4c9"
color15 = "#ffe9e7"
