accent = "#d62f4b"
cursor = "#d62f4b"
foreground = "#ffe9e7"
background = "#170306"
selection_foreground = "#170306"
selection_background = "#f3d8da"

color0 = "#22060a"
color1 = "#ffe9e7"
color2 = "#efc2c6"
color3 = "#b01732"
color4 = "#6f0d1f"
color5 = "#ffe9e7"
color6 = "#efc2c6"
color7 = "#ffe9e7"
color8 = "#6f0d1f"
color9 = "#ffe9e7"
color10 = "#efc2c6"
color11 = "#b01732"
color12 = "#d62f4b"
color13 = "#ffe9e7"
color14 = "#efc2c6"
color15 = "#ffe9e7"
