$activeBorderColor = rgba(e23f5aff)
$inactiveBorderColor = rgba(c61d3fee)

general {
    gaps_out = 0
    border_size = 0
    col.active_border = $activeBorderColor
    col.inactive_border = $inactiveBorderColor
}

group {
    col.border_active = $activeBorderColor
    col.border_inactive = $inactiveBorderColor
}
