set -g status-style "bg=default,fg=#f0d7c6"
set -g status-left "#[fg=#fff1e8,bg=#7e3d21,bold] #S #[fg=#f0d7c6,bg=default] "
set -g status-right "#[fg=#d78a59]#{?client_prefix,PREFIX ,}#{?window_zoomed_flag,ZOOM ,}#[fg=#f0d7c6]#h "
set -g window-status-format "#[fg=#d78a59] #I:#W "
set -g window-status-current-format "#[fg=#fff1e8,bg=#7e3d21,bold] #I:#W #[fg=#f0d7c6,bg=default]"
set -g pane-border-style "fg=#d78a59"
set -g pane-active-border-style "fg=#fff1e8"
set -g message-style "bg=#1a110d,fg=#fff1e8"
set -g message-command-style "bg=#1a110d,fg=#fff1e8"
set -g mode-style "bg=#7e3d21,fg=#fff1e8"
set -g popup-style "bg=#1a110d,fg=#fff1e8"
set -g popup-border-style "fg=#d78a59,bg=#1a110d"
set -g menu-style "bg=#1a110d,fg=#fff1e8"
set -g menu-selected-style "bg=#7e3d21,fg=#fff1e8"
setw -g clock-mode-colour "#d78a59"
