set -g status-style "bg=default,fg=#f2c4c9"
set -g status-left "#[fg=#ffe9e7,bg=#8f112a,bold] #S #[fg=#f2c4c9,bg=default] "
set -g status-right "#[fg=#c61d3f]#{?client_prefix,PREFIX ,}#{?window_zoomed_flag,ZOOM ,}#[fg=#f2c4c9]#h "
set -g window-status-format "#[fg=#c61d3f] #I:#W "
set -g window-status-current-format "#[fg=#ffe9e7,bg=#8f112a,bold] #I:#W #[fg=#f2c4c9,bg=default]"
set -g pane-border-style "fg=#c61d3f"
set -g pane-active-border-style "fg=#ffe9e7"
set -g message-style "bg=#3b0911,fg=#ffe9e7"
set -g message-command-style "bg=#3b0911,fg=#ffe9e7"
set -g mode-style "bg=#8f112a,fg=#ffe9e7"
set -g popup-style "bg=#3b0911,fg=#ffe9e7"
set -g popup-border-style "fg=#c61d3f,bg=#3b0911"
set -g menu-style "bg=#3b0911,fg=#ffe9e7"
set -g menu-selected-style "bg=#8f112a,fg=#ffe9e7"
setw -g clock-mode-colour "#c61d3f"
