set -g status-style "bg=default,fg=#efc2c6"
set -g status-left "#[fg=#ffe9e7,bg=#6f0d1f,bold] #S #[fg=#efc2c6,bg=default] "
set -g status-right "#[fg=#b01732]#{?client_prefix,PREFIX ,}#{?window_zoomed_flag,ZOOM ,}#[fg=#efc2c6]#h "
set -g window-status-format "#[fg=#b01732] #I:#W "
set -g window-status-current-format "#[fg=#ffe9e7,bg=#6f0d1f,bold] #I:#W #[fg=#efc2c6,bg=default]"
set -g pane-border-style "fg=#b01732"
set -g pane-active-border-style "fg=#ffe9e7"
set -g message-style "bg=#22060a,fg=#ffe9e7"
set -g message-command-style "bg=#22060a,fg=#ffe9e7"
set -g mode-style "bg=#6f0d1f,fg=#ffe9e7"
set -g popup-style "bg=#22060a,fg=#ffe9e7"
set -g popup-border-style "fg=#b01732,bg=#22060a"
set -g menu-style "bg=#22060a,fg=#ffe9e7"
set -g menu-selected-style "bg=#6f0d1f,fg=#ffe9e7"
setw -g clock-mode-colour "#b01732"
